PRL-6379: - Case party details 2
hmcts/prl-e2e-tests pull request #106
Opened 2024-10-25 10:20 UTC by abigailsmith97

[PRL-6379](https://tools.hmcts.net/jira/browse/PRL-6379)
List of pages: 

applicant/string/address/manual
applicant/string/contact-detail
applicant/string/contact-preference
respondent-details/add-respondents
User(s) to complete event: Citizen

Definition of done:

All POM sections are created
All POMs are added to a relevant journey

2024-10-25 11:29 UTC, OLT2000 commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantAddressSelectPage.ts
> +        `${Selectors.GovukErrorMessageCitizen}:text-is("${ApplicantAddressSelectContent.errorMessage}")`,
I think this is a duplicate selector. There's one called ErrorMessage which is also `.govuk-error-message`

2024-10-28 09:18 UTC, OLT2000 submitted a review, later dismissed
lgtm

2024-10-28 09:32 UTC, Scralfie approved these changes

2024-10-28 09:35 UTC, JakeCG requested changes

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactDetailPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactDetailPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactDetailPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactDetailPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactPreferencePage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactPreferencePage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/applicantContactPreferencePage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/respondentDetailsAddRespondentsPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/respondentDetailsAddRespondentsPage.ts
> +
Whitespace

2024-10-28 09:35 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/casePartyDetails/respondentDetailsAddRespondentsPage.ts
> +
Whitespace

2024-10-28 11:51 UTC, Scralfie approved these changes

2024-10-28 11:51 UTC, merged