Prl 6381
hmcts/prl-e2e-tests pull request #121
Opened 2024-10-29 12:22 UTC by Scralfie

### PRL Citizen Automation - Case party details 4

List of pages: 

respondent-details/string/address/manual
respondent-details/string/contact-details
other-person-details/other-person-check
other-person-details/add-other-persons
User(s) to complete event: Citizen

Definition of done:

All POM sections are created
All POMs are added to a relevant journey

### JIRA link

[PRL-6381](https://tools.hmcts.net/jira/browse/PRL-6381)

**Before merging a pull request make sure that:**

- [x] Commits are meaningful and simple
- [x] All commits are squashed into a single commit
- [x] README and other documentation has been updated / added (if needed)

2024-10-29 13:57 UTC, OLT2000 requested changes

2024-10-29 13:57 UTC, OLT2000 commented on e2e/journeys/citizen/createCase/C100/subJourneys/c100CasePartyDetails.ts
> +  dontKNowEmailAndTelephone: boolean;
Typo in `dontKNow`

2024-10-30 09:00 UTC, JakeCG approved these changes

2024-10-30 09:17 UTC, OLT2000 approved these changes

2024-10-30 09:21 UTC, merged