Prl 6251
hmcts/prl-e2e-tests pull request #33
Opened 2024-09-20 15:42 UTC by Scralfie

### Change description

Enter the ticket description

### JIRA link

[PRL-6251](https://tools.hmcts.net/jira/browse/PRL-6251)

**Before merging a pull request make sure that:**

- [x] Commits are meaningful and simple
- [x] All commits are squashed into a single commit
- [x] README and other documentation has been updated / added (if needed)

2024-09-25 13:56 UTC, JayAshton commented on e2e/pages/manageCases/createCase/C100/childrenAndRespondents/childrenAndRespondents1Page.ts
> +      // await AccessibilityTestHelper.run(page);
Add the ticket number as a comment for why these a11y checks are commented please

2024-09-25 14:04 UTC, JakeCG requested changes

2024-09-25 14:04 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/childrenAndRespondents/childrenAndRespondents1Page.ts
> +      Helpers.checkVisibleAndPresent(
Can you make line 67 - 94 a checkgroup instead?

2024-09-25 14:04 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/childrenAndRespondents/childrenAndRespondents1Page.ts
> +    await page.selectOption(
This should wait for the option to appear, so the waitforTimeout isn't needed

2024-09-25 14:04 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/childrenAndRespondents/childrenAndRespondents1Page.ts
> +      await this.giveDetailsOtherRelationshipStaticText(page);
Don't think this needs a separate function as it calls one command

2024-09-25 14:04 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/childrenAndRespondents/childrenAndRespondentsSubmitPage.ts
> +    await this.checkPageLoads(
Can you make both of these a Promise.all([]) so the checks run simultaneously?

2024-09-25 14:04 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100ChildrenAndRespondents.spec.ts
> +  Setting the applicant Gender to female. @crossbrowserManageCases`, async ({
Remove the @crossbrowserManageCases tag

2024-09-25 14:04 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100ChildrenAndRespondents.spec.ts
> +  Setting the applicant Gender to female. @crossbrowserManageCases`, async ({
Does this not need the @accessibilityManageCases tag?

2024-09-26 12:44 UTC, OLT2000 approved these changes
lgtm

2024-09-26 13:30 UTC, merged