Prl 6254
hmcts/prl-e2e-tests pull request #48
Opened 2024-09-26 16:43 UTC by Scralfie

### Change description

Event - C100MIAM

### JIRA link

[PRL-6254](https://tools.hmcts.net/jira/browse/PRL-6254)

**Before merging a pull request make sure that:**

- [x] Commits are meaningful and simple
- [x] All commits are squashed into a single commit
- [x] README and other documentation has been updated / added (if needed)

2024-10-01 07:58 UTC, OLT2000 submitted a review, later dismissed
lgtm

2024-10-01 08:25 UTC, JakeCG requested changes

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/fixtures/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitContent.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgrade3Page.ts
> +    for (let i = 1; i <= 22; i++) {
This is fine for now, but in future you would have a radio enum that is separate for this, and you would do a for loop thats 
`(for radio in radioButtons) {`

2024-10-01 08:25 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/miamPolicyUpgrade/miamPolicyUpgradeSubmitPage.ts
> +
Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/pages/manageCases/createCase/initialJourney/solicitorCreate4Page.ts
> -
This should actually have Whitespace

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  test(`Complete the C100 Create case MIAM as a solicitor with the following options:
Needs a gap

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  MiamSelection is attended4MonthsPrior. @crossbrowserManageCases`, async ({
Remove the tag here

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  test(`Complete the C100 Create case MIAM as a solicitor with the following options:
Needs a gap

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  Saying Yes to all options. @crossbrowserManageCases`, async ({
Remove the tag here

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  test(`Complete the C100 Create case MIAM as a solicitor with the following options:
Needs a gap

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  Saying no to all options. @crossbrowserManageCases`, async ({
Remove the tag here

2024-10-01 08:25 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100MiamPolicyUpgrade.spec.ts
> +  test(`Complete the C100 Create case MIAM as a solicitor with the following options:
Needs a gap

2024-10-02 08:04 UTC, JakeCG approved these changes

2024-10-02 08:20 UTC, OLT2000 approved these changes
lgtm

2024-10-02 08:20 UTC, merged