Prl 6257
hmcts/prl-e2e-tests pull request #53
Opened 2024-10-01 11:05 UTC by Scralfie

### Change description

Event: C100 Intenational Element

### JIRA link

[PRL-6257](https://tools.hmcts.net/jira/browse/PRL-6257)

**Before merging a pull request make sure that:**

- [x] Commits are meaningful and simple
- [x] All commits are squashed into a single commit
- [x] README and other documentation has been updated / added (if needed)

2024-10-01 13:48 UTC, JakeCG requested changes

2024-10-01 13:48 UTC, JakeCG commented on e2e/pages/manageCases/createCase/C100/internationalElement/internationalElement1Page.ts
> +  private static async fillInFields({
Needs a whitespace above

2024-10-01 13:48 UTC, JakeCG commented on e2e/tests/manageCases/createCase/C100/c100InternationalElement.spec.ts
> +  Setting the applicant Gender to male. @crossbrowserManageCases`, async ({
Remove tag

2024-10-01 13:48 UTC, OLT2000 submitted a review, later dismissed
lgtm

2024-10-02 13:21 UTC, JakeCG approved these changes

2024-10-02 13:26 UTC, OLT2000 approved these changes
lg

2024-10-02 13:26 UTC, merged