Prl 6388
hmcts/prl-e2e-tests pull request #76
Opened 2024-10-17 10:33 UTC by Scralfie

### Change description

C100 Citizen - OtherProceedings3

### JIRA link

[PRL-6388](https://tools.hmcts.net/jira/browse/PRL-6388)

**Before merging a pull request make sure that:**

- [x] Commits are meaningful and simple
- [x] All commits are squashed into a single commit
- [x] README and other documentation has been updated / added (if needed)

2024-10-18 10:33 UTC, JakeCG requested changes

2024-10-18 10:33 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/otherProceedings/supervisionDocumentUpload.ts
> +    //   `${Selectors.button}:text-is("${SupervisionDocumentUpload.uploadFile}")`,
This does need to be pressed, can you also check for the remove button being visible

2024-10-18 12:40 UTC, Louis-Solirius approved these changes

2024-10-18 13:17 UTC, Louis-Solirius approved these changes

2024-10-21 08:40 UTC, JakeCG approved these changes

2024-10-21 08:42 UTC, merged