PRL-6364
hmcts/prl-e2e-tests pull request #79
Opened 2024-10-17 14:19 UTC by Louis-Solirius

### Change description

List of pages: 

child-details/add-children?
child-details/ (Provide details for <name>)
child-details/ (Which of the decisions you’re asking the court to resolve relate to <name>)
User(s) to complete event: Citizen

Definition of done:

All POM sections are created
All POMs are added to a relevant journey

### JIRA link

[PRL-6364](https://tools.hmcts.net/jira/browse/PRL-6364)

**Before merging a pull request make sure that:**

- [ ] Commits are meaningful and simple
- [ ] All commits are squashed into a single commit
- [ ] README and other documentation has been updated / added (if needed)

2024-10-18 10:31 UTC, JakeCG requested changes

2024-10-18 10:31 UTC, JakeCG commented on e2e/journeys/citizen/createCase/C100People1/C100People1.ts
> +import { Page } from "@playwright/test";
Can you rename this file just to "People"

2024-10-18 10:31 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/people1/addChildrenPage.ts
> +import AccessibilityTestHelper from "../../../../../common/accessibilityTestHelper";
Same with this directory

2024-10-18 13:28 UTC, Scralfie submitted a review, later dismissed

2024-10-18 13:33 UTC, Scralfie approved these changes

2024-10-18 15:56 UTC, abigailsmith97 approved these changes
lgtm

2024-10-21 09:03 UTC, JakeCG requested changes

2024-10-21 09:03 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/people/provideDetailsPage.ts
> +enum radioIds {
Missing hashes here

2024-10-21 09:03 UTC, JakeCG commented on e2e/pages/citizen/createCase/C100/people/provideDetailsPage.ts
> +enum inputIds {
Missing hashes here

2024-10-21 09:07 UTC, Louis-Solirius commented on e2e/pages/citizen/createCase/C100/people/provideDetailsPage.ts
> +enum radioIds {
whoops

2024-10-21 09:59 UTC, GauravChawlaMOJ approved these changes

2024-10-21 09:59 UTC, merged